### Numpy
- 데이터는 행열로 표현
- 행열 데이터 빠르게 계산 해야 합니다.
- 행열 데이터 생성, 수정, 계산등을 빠르게 처리해주는 패키지
- 특징
    - C, C++, 포트란로 장성
    - 선형대수학을 빠르게 연산
        - scalar, vector, matrix(행렬)
            - 1,2,3 -> scalar
            - [1,2,3] -> vector
            - [(1.2), (3,4)] -> matrix (행과 열이 존재)
- 기본적인 기능
    - np.array의 타입: ndarray
    - array.dtype: 원소 타입 확인
    - array.astype(타입): 원소 타입 재정의
    - array.ndim: 배열의 차원 수
    - array.shape: 배열의 각 차원의 크기를 tuple 형태로 표기
    - array.reshape: 차원 재정의
    - offset index
    - 조건 선택 가능
        - idx = array > 3
        - array[idx]
    - 데이터 생성
        - np.zeros(matrix)
        - np.ones(matrix)
        - np.range(1,7)
    - 브로드 캐스팅 가능 (흩뿌리고 퍼뜨리고 전파)

###  Summary
- numpy: 선형대수를 빠르게 연산해주는 패키지
- 행열의 생성 1: ndarray, np.array(iterable)
- 행열의 생성 2: ones, zeros
- 행열 데이터 선택: array[x,y,z]
- 행열 데이터 수정
    - 행열 데이터를 선택
    - =,> (값(scalar, vector, matrix))
    - 브로드 캐스팅 개념
- arange: list에서 사용하는 range, but 결과 type: ndarray

In [1]:
import numpy as np

In [2]:
# 행렬 데이터 생성
# ndarray: 한가지 데이터 타입만 값으로 사용이 가능
# shape: 배열의 각 차원의 크기를 tuple 형태로 표기
# ndim: 배열의 차원 수

In [3]:
array = np.array([1, 2, 3])
type(array), array

(numpy.ndarray, array([1, 2, 3]))

In [8]:
array2 = np.array(
    [[1, 2, 3],
    [4, 5, 6]],
)
type(array2), array2, array2.ndim, array2.shape

(numpy.ndarray,
 array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [14]:
# 행렬의 모양(shape) 변경하기
array2.reshape(3,2,1)

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [ ]:
# 행렬 데이터의 선택: offset index: masking

In [15]:
array2[1][::-1]

array([6, 5, 4])

In [16]:
# 데이터 수정

In [19]:
array2[0][1] = 7
array2

array([[1, 7, 3],
       [4, 5, 6]])

In [21]:
array2[0] = [6,7,8]
array2

array([[6, 7, 8],
       [4, 5, 6]])

In [22]:
#조건으로 선택
idx = array2 > 7
idx

array([[False, False,  True],
       [False, False, False]])

In [24]:
array2[idx]

array([8])

In [25]:
array2[idx] = 100
array2

array([[  6,   7, 100],
       [  4,   5,   6]])

In [26]:
# 행렬의 데이터 생성2

In [27]:
data = np.zeros((2,3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
# 데이터 타입 바꾸기
data.dtype

dtype('float64')

In [31]:
data2 = data.astype("int")
data2

array([[0, 0, 0],
       [0, 0, 0]])

In [32]:
data3 = np.ones((2,3,2))
data3

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])