### Numpy
- 데이터는 행열로 표현
- 행열 데이터 빠르게 계산을 해야 합니다.
- 행열 데이터 생성, 수정, 곗ㄴ등을 빠르게 처리해주는 패키지
- 특징
    - C,C++, 포트란로 작성
    - 선형 대수학을 빠르게 연산
        - 스칼라, 벡터, 매트릭스

### Summary
- Numpy 란?
    - 다차원 배열을 쉽게 처리하고 효율적으로 사용할수 있도록 지원한 파이썬 패키지
    - 이외 에도 수치계산을 위해 효율적으로 구현된 기능 제공
    - C의 배열
- 데이터 선택
    - array[1,2] = array[1][2]
    - array2[array2 > 7]
- 브로드 캐스팅
    - array2[0] = 0 행 일괄 변경 가능
- 행열의 생성
    - np.array()
        - np.array([1,2,3]): 아규먼트: 리스트 or 튜플
    - np.arange() : 아규먼트는 range와 동일, type: ndarray
        ```
        np.arange(5) # [0, 1, 2, 3, 4]
        np.arange(5,10) # [5, 6, 7, 8, 9]
        np.arange(1, 11,2) # [1, 3, 5, 7, 9]
        ```
    - np.ones() : dtype = none
        - np.ones((4, 3, 2), dtype = int)
            - 3행 2열의 배열을 4개 만들고 데이터는 전부 1로 넣어줌
    - np.zeros() : dtype = float
        - np.zeros((2, 3))
            - 아규먼트는 ones와 비슷, 2행 3열의 배열에 데이터 전부 0
    - np.random.randint(100, 130, size=(8, 8))
    - np.linspace(0, 100, 5, dtype = int) # [  0,  25,  50,  75, 100]
        - 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
    - np.logspace(2, 4, 3, dtype = int) # [  100,  1000, 10000]
        - log10(x1)=2, log10(x2)=3, log10(x3)=4
        - 설정한 범위에서 로그로 분할한 위치의 값을 출력
- 변수
    - dtype : numpy array 의 데이터의 type 반환
    - shape : numpy array 의 obejct dimension 구성을 tuple 형태로 반환
    - ndim : 차원 반환
    - size : data 의 개수
    ```
    float64
    (4,)
    1
    4
    ```
- 다양한 함수
    - data.reshape(): 행열 변형, Array 의 shape 의 크기를 변경함 (이때, element 의 갯수는 동일)
        - size 만 같다면 다차원으로 자유로이 변형가능
    - data.astype("int"): 행열의 자료형 변환
    - np.min(datas), np.max(datas)
    - numpy.unique(arr, return_index, return_inverse, return_counts):
        - 입력된 배열에서 중복되지 않는 고유한 요소들의 배열을 리턴
        - arr: 1차원 배열이 아니면 병합
        - return_index: 값이 True면 입력 배열의 요소들의 인덱스들을 리턴
        - return_inverse: 값이 True면 입력 배열을 재구성할 떄 쓰이는 고유 배열의 인덱스들을 반환
        - return_counts: 값이 True면 중복 되지 않는 요소들이 입력 배열에 나타난 회 수를 리턴
- 결합
    - np.concatenate((na1, na3)) 세로로 결합
    - np.concatenate((na2, na3), axis=1)
    - np.c_[np.array([1,2,3]), np.array([4,5,6])]
        - c_[]: 두개의 배열을 열의 형태로 바꾼뒤 더한다
        
        ```
        [[1, 4],
       [2, 5],
       [3, 6]]
        ```
     - np.r_[np.array([1,2,3]), np.array([4,5,6])]
         - r_[]: 행의 형태로 더한다
         - 결과: [1, 2, 3, 4, 5, 6]
- numpy random
    - seed : 랜덤값을 설정값, 챔스 조 추첨하듯 같은 시드권에서는 같은 값이 나옴
    
        ```
        np.random.seed(1)
        result2 = np.random.randint(10, 100, 10)

        np.random.seed(2)
        result3 = np.random.randint(10, 100, 10)
        ``` 
    - rand : 균등분포로 0 ~ 1사이 난수를 발생
        - np.random.rand(3)
        - result => [0.29323324, 0.31151808, 0.58479854]
    - randn : 정규분포로 난수를 발생
    - randint : 균등분포로 정수값을 발생
        - np.random.randint(1, 10, (3, 4))
    - suffle : 행렬 데이터를 섞어 줍니다.
        - np.random.shuffle(np)
    - choice : 특정 확률로 데이터를 선택
        - np.random.choice(5, 10, p=[0.1, 0, 0.4, 0.2, 0.3])
    

In [24]:
# 행렬 데이터 생성
# ndarray : 한가지 데이터 타입만 값으로 사용이 가능
array = np.array([1,2,3])
type(array), array

(numpy.ndarray, array([1, 2, 3]))

In [25]:
array2 = np.array(
    [[1, 2, 3],
    [4, 5, 6]]
)
array2, array2.ndim, array2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [26]:
# 행렬의 모양(shape) 변경하기
array2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
# 행렬 데이터의 선택: offsef index

In [28]:
array2[1][::1]

array([4, 5, 6])

In [29]:
array2[1,2] # array2[1][2]

6

In [30]:
# 데이터 수정

In [31]:
array2[0][1] = 7
type(array2), type(array2[0]), type(array2[0][0])

(numpy.ndarray, numpy.ndarray, numpy.int32)

In [32]:
# 브로드캐스팅
array2[0] = 0 # 행의 데이터 일괄 변경 가능
print(array2)

[[0 0 0]
 [4 5 6]]


In [34]:
array2[0] = [9,10,11]
array2

array([[ 9, 10, 11],
       [ 4,  5,  6]])

In [37]:
#  조건으로 선택
idx = array2 > 7

In [50]:
array2[array2 > 7]

array([ 9, 10, 11])

In [44]:
# 행렬데이터의 생성 2
# np.zeros((2, 3)) -> 0으로 가득찬 2행 3열
# np.ones((4, 3, 2)) -> 3행 2열 4개
# dtype: 자료형 반환
# data.astype(자료형): 자료형 변경
data = np.zeros((2, 3))
data, data.dtype

(array([[[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]]]),
 dtype('float64'))

In [46]:
data = data.astype("int")
data

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [49]:
data = np.ones((3, 3, 3), dtype = int)
data

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [48]:
# 행열 데이터 생성 3
# np.arrange
np.arange(5) # [0, 1, 2, 3, 4]
np.arange(5,10) # [5, 6, 7, 8, 9]
np.arange(1, 11,2) # [1, 3, 5, 7, 9]

array([1, 3, 5, 7, 9])