###  Summary
- numpy: 선형대수를 빠르게 연산해주는 패키지
- 행열의 생성 1: ndarray, np.array(iterable)
- 행열의 생성 2: ones, zeros
- 행열 데이터 선택: array[x,y,z]
- 행열 데이터 수정
    - 행열 데이터를 선택
    - =,> (값(scalar, vector, matrix))
    - 브로드 캐스팅 개념
- arange: list에서 사용하는 range, but 결과 type: ndarray

### quiz 
- 100 ~ 130 까지 랜덤한 숫자를 가지는 8*8 행렬을 만들고,
- 3의 배수는 fiz, 5의 배수는 buz, 3과 5의 배수는 fbz 문자 변환 
- 위의 조건에 맞지 않는 데이터느 ㄴ랜덤하게 생성된 정수로 출력
- 랜덤한 행렬 데이터

```
datas = np.random.randint(100, 130, size=(8, 8))
```
- 데이터 타입이 정수 -> 문자열: ndarray.astype()

In [4]:
import numpy as np

In [49]:
datas = np.random.randint(100, 130, (8, 8))
datas

array([[122, 106, 114, 104, 129, 105, 128, 122],
       [103, 106, 111, 105, 108, 119, 117, 106],
       [104, 107, 104, 115, 121, 101, 105, 106],
       [113, 124, 119, 106, 128, 116, 104, 108],
       [111, 102, 106, 129, 106, 118, 122, 124],
       [118, 100, 124, 108, 124, 113, 114, 117],
       [113, 106, 116, 107, 121, 125, 122, 128],
       [121, 113, 109, 102, 102, 110, 105, 123]])

In [50]:
data1 = np.array([1,2,3])
data2 = [True, False, True]
data1[data2]

array([1, 3])

In [51]:
# 3의 배수, 5의 배수, 15의 배수 위치값에 대한 T, F matrix 생성
# 확인: datas[datas % 3 == 0]
idx_3 = datas % 3 == 0
idx_5 = datas % 5 == 0
idx_15 = datas % 15 == 0

In [52]:
# 데이터의 타입을 str로 변환
result = datas.astype("str")

In [53]:
# T, F matrix를 이용하여 특정 조건의 데이터를 선택 후 브로드 캐스팅하게 값을 대입
result[idx_3] = "fiz"
result[idx_5] = "buz"
result[idx_15] = "fbz"

In [54]:
result

array([['122', '106', 'fiz', '104', 'fiz', 'fbz', '128', '122'],
       ['103', '106', 'fiz', 'fbz', 'fiz', '119', 'fiz', '106'],
       ['104', '107', '104', 'buz', '121', '101', 'fbz', '106'],
       ['113', '124', '119', '106', '128', '116', '104', 'fiz'],
       ['fiz', 'fiz', '106', 'fiz', '106', '118', '122', '124'],
       ['118', 'buz', '124', 'fiz', '124', '113', 'fiz', 'fiz'],
       ['113', '106', '116', '107', '121', 'buz', '122', '128'],
       ['121', '113', '109', 'fiz', 'fiz', 'buz', 'fbz', 'fiz']],
      dtype='<U11')

### Quiz
- 1~ 20까지 랜덤한 숫자를 가지는 5*5 행렬 생성
- 최대값에는 MAX, 최소값에는 MIN 문자열이 들어가도록 치환하는 코드
- 최대값과 최소값 함수

```
np.min(ndarray), np.max(ndarray)
```

In [55]:
import numpy as np

In [59]:
datas = np.random.randint(1,20, size=(5,5))
datas

array([[ 6, 19,  4, 16,  6],
       [10,  1, 12, 16,  3],
       [ 2, 10, 14, 12, 18],
       [ 6, 12, 19, 14, 13],
       [ 1, 18, 13,  2, 17]])

In [67]:
idx_min, idx_max = datas == np.min(datas), datas == np.max(datas)

In [68]:
result = datas.astype("str")
result

array([['6', '19', '4', '16', '6'],
       ['10', '1', '12', '16', '3'],
       ['2', '10', '14', '12', '18'],
       ['6', '12', '19', '14', '13'],
       ['1', '18', '13', '2', '17']], dtype='<U11')

In [69]:
result[idx_min] = "MIN"
result[idx_max] = "MAX"

In [70]:
result

array([['6', 'MAX', '4', '16', '6'],
       ['10', 'MIN', '12', '16', '3'],
       ['2', '10', '14', '12', '18'],
       ['6', '12', 'MAX', '14', '13'],
       ['MIN', '18', '13', '2', '17']], dtype='<U11')

### 1. linspace, logspace 함수
- linspace: 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
- logspace: 설정한 범위에서 로그로 분할한 위치의 값을 출력
    - `np.logspace(np.log10(age_30), np.log10(age_60), 4)`

In [71]:
# linspace
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [73]:
# logspace
# log10(x1)=2, log10(x2)=3, log10(x3)=4
np.logspace(2, 4, 3)

array([  100.,  1000., 10000.])

In [ ]:
# 30세에 연봉이 $100000 이고 60세의 연봉이 $1000000 일때
# 연봉이 선형으로 증가, 지수함수로 증가하는 두 경우에서의 40세, 50세 연봉을 출력

In [74]:
age_30 = 100000
age_60 = 1000000

In [75]:
np.linspace(age_30, age_60, 4)

array([ 100000.,  400000.,  700000., 1000000.])

In [76]:
np.logspace(np.log10(age_30), np.log10(age_60), 4)

array([ 100000.        ,  215443.46900319,  464158.88336128,
       1000000.        ])

### 2. numpy random
- seed: 랜덤값을 설정값
- rand: 균등분포로 난수를 발생 0~1 사이의 값
- randn: 정규분포로 난수를 발생
- randint: 균등분포로 정수값을 발생
- shuffle: 행렬 데이터를 섞어 줍니다.
- choice: 특정 확률로 데이터를 선택
- unique: 행열에 몇번나왔는지 확인

In [78]:
# seed
np.random.seed(1)
result1 = np.random.randint(10, 100, 10)

np.random.seed(1)
result2 = np.random.randint(10, 100, 10)

np.random.seed(2)
result3 = np.random.randint(10, 100, 10)

result1, result2, result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [80]:
# rand
np.random.rand(10), np.random.randn(10)

(array([0.85397529, 0.49423684, 0.84656149, 0.07964548, 0.50524609,
        0.0652865 , 0.42812233, 0.09653092, 0.12715997, 0.59674531]),
 array([-0.33882197, -0.23618403, -0.63765501, -1.18761229, -1.42121723,
        -0.1534952 , -0.26905696,  2.23136679, -2.43476758,  0.1127265 ]))

In [82]:
# shuffle
r = np.random.randint(1, 10, (3,4))
r

array([[9, 3, 7, 6],
       [7, 7, 7, 4],
       [9, 3, 2, 5]])

In [88]:
np.random.shuffle(r)
r

array([[9, 3, 2, 5],
       [9, 3, 7, 6],
       [7, 7, 7, 4]])

In [89]:
# choice
np.random.choice(5, 10, p=[0.1, 0, 0.4, 0.2, 0.3])

array([4, 4, 4, 3, 4, 2, 2, 3, 2, 0])

In [91]:
# unique
numbers, counts = np.unique(r, return_counts=True)
print(numbers)
print(counts)

[2 3 4 5 6 7 9]
[1 2 1 1 1 4 2]


### 3. 행렬데이터의 결합
- concatenate
- 매개변수중 axis=0(default): 세로결합, axis=1: 가로결합

In [99]:
na1 = np.random.randint(10, size=(2, 3))
na2 = np.random.randint(10, size=(3, 2))
na3 = np.random.randint(10, size=(3, 3))
na1, na2, na3

(array([[0, 7, 1],
        [8, 9, 0]]),
 array([[7, 0],
        [5, 2],
        [5, 1]]),
 array([[3, 3, 1],
        [8, 6, 8],
        [1, 5, 7]]))

In [100]:
# 세로 결합
np.concatenate((na1,na3))

array([[0, 7, 1],
       [8, 9, 0],
       [3, 3, 1],
       [8, 6, 8],
       [1, 5, 7]])

In [101]:
# 가로결합
np.concatenate((na2,na3), axis=1)

array([[7, 0, 3, 3, 1],
       [5, 2, 8, 6, 8],
       [5, 1, 1, 5, 7]])